---
title: "Add District to Block Groups"
author: "Chris Day"
date: "2023-02-08"
output: html_document
---

```{r}
library(tidyverse)
library(sf)
library(mapview)
library(jsonlite)
```

## Select Year
```{r}
config <- fromJSON("config.json")
config_year <- config$year
config_bg_year <- config$bg_year
```


## Inputs
```{r}
#block groups
bg <- st_read(paste0("data/data",config_year,"/tl_",config_bg_year,"_49_bg/tl_",config_bg_year,"_49_bg.shp")) %>%
  st_transform(26912) 
bgc <- bg %>% st_centroid()

#geoid geography
geo <- bg %>% select(GEOID)

#small districts
sd <- st_read(paste0("data/data",config_year,"/Dist_Small/Dist_Small.shp")) 
sdc <- sd %>% st_centroid()

#medium districts
md <- st_read(paste0("data/data",config_year,"/Dist_Medium/Dist_Medium.shp")) 
mdc <- md %>% st_centroid()

#large districts
ld <- st_read(paste0("data/data",config_year,"/Dist_Large/Dist_Large.shp")) 
ldc <- ld %>% st_centroid()

#counties
counties_shp <- st_read(paste0("data/data",config_year,"/Utah_County_Boundaries-shp/Counties.shp"))
```

## Add State and County Fips to Small District Geography
```{r}
#counties
counties <- counties_shp %>%
  mutate(STATEFP20 = '49', 
         COUNTYFP20 = ifelse(nchar(FIPS) == 1, paste0("00",FIPS),paste0("0",FIPS))) %>%
  select(STATEFP20,COUNTYFP20) %>%
  st_transform(26912) 

#join county/state data to small districts
sdco <- st_join(sdc, counties, join = st_within) %>%
  as_tibble() %>%
  select(-geometry) %>%
  left_join(sd) %>%
  st_as_sf()

st_write(sdco, paste0("data/data",config_year,"/Dist_Small/Dist_Small_Counties.shp"),delete_dsn = TRUE)
```
## Add State and County Fips to Medium District Geography
```{r}
#join county/state data to small districts
mdco <- st_join(mdc, counties, join = st_within) %>%
  as_tibble() %>%
  select(-geometry) %>%
  left_join(md) %>%
  st_as_sf()

st_write(mdco, paste0("data/data",config_year,"/Dist_Medium/Dist_Medium_Counties.shp"),delete_dsn = TRUE)
```
## Add State and County Fips to Large District Geography
```{r}
#join county/state data to small districts
ldco <- st_join(ldc, counties, join = st_within) %>%
  as_tibble() %>%
  select(-geometry) %>%
  left_join(ld) %>%
  st_as_sf()

st_write(ldco, paste0("data/data",config_year,"/Dist_Large/Dist_Large_Counties.shp"),delete_dsn = TRUE)
```

## Join Small District Data to Block Groups
```{r}
bgsd <- st_join(bgc, sd, join = st_within) %>%
  select(STATEFP, COUNTYFP, TRACTCE, DISTSML, DSML_NAME,DISTMED, DMED_NAME, DISTLRG, DLRG_NAME, BLKGRPCE, GEOID, NAMELSAD, MTFCC, FUNCSTAT, ALAND, AWATER, INTPTLAT, INTPTLON, geometry) %>%
  select(-5) %>%
  as_tibble() %>%
  select(-geometry) %>%
  left_join(geo) %>%
  st_as_sf()

st_write(bgsd, paste0("data/data",config_year,"/tl_",config_bg_year,"_49_bg/tl_",config_bg_year,"_49_sd_bg.shp"),delete_dsn = TRUE)
```


## View Mapss
```{r}
mapview(sdco) +
  mapview(bgc)
```

```{r}
mapview(bgsd)
```



