---
title: "Process LEHD for Commute Patterns"
author: "Chris Day"
date: "2023-01-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(foreign)
library(sf)
library(jsonlite)
library(mapview)
library(imputeTS)
```

## Select Year of Analysis
```{r}
year = '2018'
```


## Data
```{r}
#read in the LEHD data
lehd_raw <- read_csv(paste0("data/data",year,"/ut_od_main_JT00_",year,".csv")) %>%
  select(w_geocode, h_geocode, S000) # S000 is Number of Jobs
```

```{r}
#read in township codes and adjust the shortdesc to make merging easier later on
township_codes <- read_csv("data/data2019/citytownship.csv") %>%
  select(1,2) %>%
  mutate(SHORTDESC = case_when(
    CODE3 == "EMT" ~ "Emigration Canyon",
    CODE3 == "CMT" ~ "Copperton",
    CODE3 == "KMT" ~ "Kearns",
    CODE3 == "MMT" ~ "Magna",
    CODE3 == "WHT" ~ "White City",
    TRUE ~ SHORTDESC
  ))
```

```{r}
#read in the uofu adjustment factors
uofu_adj <- read_csv("data/data2018/490351108004_Manual_Allocation.csv") %>%
  mutate(GEOID = as.factor(GEOID))
```

```{r}
# a list of all the city/townships in the wfrc areas
wfrc_towns <- c("AFK","ALA","ALP","BDL","BGM","BNT","BRT","CDF","CEN","CHA","CHL","CLF","CLI","CMT","COA","CWH","DAN","DRA","EAG","ELK","EMT","FAR","FCS","FFD","FRR","FTH","GLA","GOS","GRL","HAR","HDT","HDT","HEB","HER","HGH","HNF","HOL","HOO","HVL","IND","INT","KAY","KMS","KMT","LAY","LEH","LIN","MAP","MID","MLC","MMT","MRG","MSL","MUR","MWY","NOG","NSL","OGD","OKL","ORM","PAY","PGR","PLN","PRK","PRY","PVO","PVW","ROY","RVD","RVT","SAN","SAQ","SAR","SFK","SJC","SLC","SLM","SOG","SPV","SSL","SUN","SWE","SYR","TAY","TOO","UIN","VIN","WAT","WBG","WDL","WEB","WHT","WHV","WIL","WJC","WPT","WVC","WXC")

```

## Geographic Data
```{r}
# block level coordinates
blockcity <- read.dbf("data/data2019/blockcentersWBlockGroup.dbf") %>%
  select(GEOID, GEOID10,x,y) %>% st_as_sf(coords = c("x","y"), crs = 4326) %>%
  st_transform(crs = 4326) %>%   
  st_as_sf() %>%
  st_transform(26912) 
```

```{r}
# township shapefile
sf_townships <- st_read("data/data2019/Municipalities_Township/Municipalities_Township.shp") %>%
  st_transform(crs = 4326) %>%   
  st_as_sf() %>%
  st_transform(26912) 

mapview(blockcity) + 
  mapview(sf_townships, color = "grey40")
```

## Merge Townships and Blockgroups
```{r}
# get the township that corresponds to each block point
blockpoint_city <- st_join(blockcity, sf_townships, join = st_within)
blockpoint_city_full <- blockpoint_city %>%
  select(GEOID, GEOID10, COUNTYNBR, NAME, SHORTDESC) %>%
  left_join(township_codes, by = c("SHORTDESC" = "SHORTDESC")) %>%
  select(GEOID10, CODE3, SHORTDESC) %>%
  mutate(GEOID10 = as.numeric(as.character(GEOID10))) %>%
  mutate(CODE3 = ifelse(is.na(CODE3), "XXX", CODE3),
         SHORTDESC = ifelse(is.na(SHORTDESC), "Outside Area", SHORTDESC))

# get the township block point data that corresponds to the wfrc modeling area
blockcity_wfrc <- blockpoint_city_full %>% 
  mutate(CODE3 = ifelse(CODE3 %in% wfrc_towns, CODE3, "XXX"),
         SHORTDESC = ifelse(CODE3 %in% wfrc_towns, SHORTDESC, "Outside WFRC Area"))
```

## Process LEHD data at the Block level for home/work locations
```{r}
# get home/work number of jobs at blockpoint city level
homeside <- left_join(lehd_raw,blockpoint_city_full, by = c("h_geocode" = "GEOID10")) %>%
  mutate(h_geocode = as.character(h_geocode), w_geocode = as.character(w_geocode))
workside <- left_join(lehd_raw,blockpoint_city_full, by = c("w_geocode" = "GEOID10")) %>%
  mutate(h_geocode = as.character(h_geocode), w_geocode = as.character(w_geocode))

# get home/work number of jobs at blockpoint city level for the wfrc modeling area
homeside_wfrc <- homeside %>%
  mutate(CODE3 = ifelse(CODE3 %in% wfrc_towns, CODE3, "XXX"),
         SHORTDESC = ifelse(CODE3 %in% wfrc_towns, SHORTDESC, "Outside WFRC Area"))
workside_wfrc <- workside %>%
  mutate(CODE3 = ifelse(CODE3 %in% wfrc_towns, CODE3, "XXX"),
         SHORTDESC = ifelse(CODE3 %in% wfrc_towns, SHORTDESC, "Outside WFRC Area"))
```

## Summarize LEHD-Blockpoint data for Python Script
```{r}
# get every possible combination of block geoids and city/township
blockseq <-  homeside_wfrc %>% 
  left_join(blockcity, by = c("w_geocode" = "GEOID10")) %>%
  expand(GEOID, CODE3 = (c(wfrc_towns,"XXX")))
```

```{r}
# summarize home-based job data at the blockpoint-city/township level -- including totals
# {CODE3}_h represents number of workers who have a home location in city/town
homeside_wide <- homeside_wfrc %>%
  left_join(blockcity, by = c("w_geocode" = "GEOID10")) %>%
  select(-SHORTDESC, -h_geocode) %>%
  group_by(GEOID, CODE3) %>%
  summarize(SumS000 = sum(S000)) %>% ungroup() 
homeside_wide_full <- blockseq %>%
  left_join(homeside_wide)%>%
  complete(GEOID,CODE3) %>%
  arrange(CODE3) %>%
  pivot_wider(names_from = CODE3, values_from = SumS000, values_fn = sum, names_glue = "{CODE3}_h") %>%
  na_replace(0)
homeside_wide_ttl <- homeside_wide_full %>% as.tibble() %>%
  mutate(TTL_h = rowSums(.[2:99])) %>%
  select(-XXX_h)
```

```{r}
# summarize work-based job data at the blockpoint-city/township level -- including totals
# {CODE3}_w represents number of workers who have a work location in city/town
workside_wide <- workside_wfrc %>%
  left_join(blockcity, by = c("h_geocode" = "GEOID10")) %>%
  select(-SHORTDESC, -w_geocode) %>%
  group_by(GEOID, CODE3) %>%
  summarize(SumS000 = sum(S000)) %>% ungroup()
workside_wide_full <- blockseq %>%
  left_join(workside_wide)%>%
  complete(GEOID,CODE3) %>%
  arrange(CODE3) %>%
  pivot_wider(names_from = CODE3, values_from = SumS000, values_fn = sum, names_glue = "{CODE3}_w") %>%
  na_replace(0)
workside_wide_ttl <- workside_wide_full %>% as.tibble() %>%
  mutate(TTL_w = rowSums(.[2:99])) %>% 
  select(-XXX_w)
```

```{r}
# merge home and work based data into single dataframe
home_work_ttl <- left_join(homeside_wide_ttl, workside_wide_ttl)
```

```{r}
# calculate a fakeid, adjust for the UofU bad allocation, and calculate a column sum after adjusting for UofU allocation
results_at_blockgroups <- home_work_ttl %>%
  mutate(fakeid = row_number() - 1) %>%
  select(198,1:197) %>%
  #adjust for UofU bad allocation
  subset(GEOID !=  "490351108004") %>%
  bind_rows(uofu_adj) %>%
  arrange(fakeid) %>%
bind_rows(summarise(.,
                    across(where(is.numeric), sum),
                    across(where(is.factor), ~"colSUM"))) %>%
  slice(n(),1:(n()-1)) %>%
  mutate(fakeid = ifelse(GEOID == "colSUM", 0,fakeid))
```


## Result
```{r}
#write output csv to be used in the python script which create the webapp inputs
write_csv(results_at_blockgroups, paste0("data/data",year,"/lehd_at_blockgroup_level",year,".csv"))
```

